# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "i2c-dev" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/2b33b778-26c6-44df-8504-22081169e03e";
      fsType = "btrfs";
      options = [ "subvol=root" "noatime" ];
    };

  boot.initrd.luks = {
    devices = {
      "encd1" = {
        device = "/dev/disk/by-uuid/fae956a3-677e-4bc8-8dc5-00885653a5fc";
        allowDiscards = true;
      };
      "encs1" = {
        device = "/dev/disk/by-uuid/38daf491-9ccc-4569-a01e-a9410c50e680";
        allowDiscards = true;
      };
      "encd2" = {
        device = "/dev/disk/by-uuid/b75fc1b5-0c5f-4d57-92b1-9e59167ad96d";
        allowDiscards = true;
      };
      "encs2" = {
        device = "/dev/disk/by-uuid/c9fe422d-0f4f-4a9e-938b-161a573ac05e";
        allowDiscards = true;
      };
    };
    reusePassphrases = true;
  };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/2b33b778-26c6-44df-8504-22081169e03e";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" "noatime" ];
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/2b33b778-26c6-44df-8504-22081169e03e";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/persist" =
    {
      device = "/dev/disk/by-uuid/2b33b778-26c6-44df-8504-22081169e03e";
      fsType = "btrfs";
      options = [ "subvol=persist" "compress=zstd" "noatime" ];
    };

  fileSystems."/var/lib" =
    {
      device = "/dev/disk/by-uuid/2b33b778-26c6-44df-8504-22081169e03e";
      fsType = "btrfs";
      options = [ "subvol=var-lib" "compress=zstd" "noatime" ];
      neededForBoot = true;
    };

  fileSystems."/var/log" =
    {
      device = "/dev/disk/by-uuid/2b33b778-26c6-44df-8504-22081169e03e";
      fsType = "btrfs";
      options = [ "subvol=var-log" "compress=zstd" "noatime" ];
      neededForBoot = true;
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/1965-7043"; # Second disk /dev/disk/by-uuid/1965-7043
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/b03a866c-effb-48e7-a6b5-5c86b625df87"; }
      { device = "/dev/disk/by-uuid/9ffa2470-9195-4853-862b-57b01a5ae3eb"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
