# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3f775e6a-b75a-49ac-afed-2f255c4d73b9";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  boot.initrd.luks = {
    devices = {
      "encd1" = {
        device = "/dev/disk/by-uuid/24d2d242-11be-4c34-90ad-8913e56ccebe";
        allowDiscards = true;
      };
      "encd2" = {
        device = "/dev/disk/by-uuid/24d2d242-11be-4c34-90ad-8913e56ccebe";
        allowDiscards = true;
      };
      "encs1" = {
        device = "/dev/disk/by-uuid/b9b33b76-07d1-464b-bd41-c1f660ae6990";
        allowDiscards = true;
      };
      "encs2" = {
        device = "/dev/disk/by-uuid/d2207b37-e6db-493f-8596-35ebe7997cf0";
        allowDiscards = true;
      };
    };
    reusePassphrases = true;
  };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/3f775e6a-b75a-49ac-afed-2f255c4d73b9";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/3f775e6a-b75a-49ac-afed-2f255c4d73b9";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/3f775e6a-b75a-49ac-afed-2f255c4d73b9";
      fsType = "btrfs";
      options = [ "subvol=persist" "compress=zstd" "noatime" ];
    };

  fileSystems."/var/lib" =
    { device = "/dev/disk/by-uuid/3f775e6a-b75a-49ac-afed-2f255c4d73b9";
      fsType = "btrfs";
      options = [ "subvol=var-lib" "compress=zstd" "noatime" ];
      neededForBoot = true;
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/3f775e6a-b75a-49ac-afed-2f255c4d73b9";
      fsType = "btrfs";
      options = [ "subvol=var-log" "compress=zstd" "noatime" ];
      neededForBoot = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D891-634B";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b07772d3-f9dc-416e-a47c-d3f68934b13b"; }
      { device = "/dev/disk/by-uuid/fc0e335d-7e1a-4045-89dd-615e72f73a79"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
