# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];
  
  i18n.defaultLocale = "de_DE.UTF-8";

  services.displayManager = {
    autoLogin.enable = true;
	  autoLogin.user = "ltrost";
  };

  # TODO
}
